<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOOIp2do\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOOIp2do/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOOIp2do.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOOIp2do\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOOIp2do\App_KernelDevDebugContainer([
    'container.build_hash' => 'OOIp2do',
    'container.build_id' => '3e13a0cc',
    'container.build_time' => 1776509938,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOOIp2do');
