<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerItHTDx2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerItHTDx2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerItHTDx2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerItHTDx2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerItHTDx2\App_KernelDevDebugContainer([
    'container.build_hash' => 'ItHTDx2',
    'container.build_id' => 'bbd1190b',
    'container.build_time' => 1776627520,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerItHTDx2');
