<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJH7exOe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJH7exOe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJH7exOe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJH7exOe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJH7exOe\App_KernelDevDebugContainer([
    'container.build_hash' => 'JH7exOe',
    'container.build_id' => 'd2eb80ac',
    'container.build_time' => 1776255403,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJH7exOe');
